---
- name: Practice using archives
  hosts: database
  become: yes
  
  tasks:
  - name: Create database_list
    shell:
      cmd: "echo dev,test,qa,prod > /mnt/mysql_backups/database_list.txt"

  - name: Create archive
    archive:
      path: /mnt/mysql_backups/database_list.txt
      dest: /mnt/mysql_backups/database_list.tar.gz
      format: gz
      force_archive: true
