- hosts: database
  become: yes
  tasks:
  - name: Create fact directory
    file:
      path: /etc/ansible/facts.d/
      state: directory
   
  - name: Create a static custom fact foo
    copy:
      content: |
        {
          "server_role": "mysql"
        }
      dest: /etc/ansible/facts.d/custom.fact

  - name: Gather new facts
    setup:

  - name: Print fact
    debug:
      msg: '"{{ ansible_local.custom.server_role }}"'
