---
- name: Ram checks
  hosts: all
  become: yes
  
  tasks:
  - name: edit vm.swqppiness 
    sysctl:
      name: vm.swappiness
      value: '10'
      state: present
    when: ansible_memory_mb.real.total > 2048

  - name: alert
    debug:
      msg: Host is low on ram
    when: ansible_memory_mb.real.total <= 2048
